### ISSUE TITLE
Improve npm installation

### ISSUE THREAD

**Issue by AntonPetrov** [PDBeurope/pdbe-molstar#1]
Thanks for the great visualisation tool! While integrating it into RNAcentral I noticed that the package is [published on npm](https://www.npmjs.com/package/pdbe-molstar) but `npm i pdbe-molstar` is not useful because there are no pre-built `dist` files.

I know that the js and css files can be loaded directly from `https://www.ebi.ac.uk/pdbe/pdb-component-library/` but I prefer to gzip and minify all assets on server side.

Could you please look into improving npm support? Let me know if you need more information.

**Comment by mandarsd** [comment]
Thanks for the feedback Anton. There are plans to improve the build and deployment process. I'll include this one in the sprint as well.

**Comment by LivC182** [comment]
@AntonPetrov I downloaded the repo and tried to install it like this:
npm install 
npm run build 
and it failed with the following error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pdbe-molstar@0.1.0 build-webpack: `webpack --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pdbe-molstar@0.1.0 build-webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liviucopoiu/.npm/_logs/2020-06-01T16_10_37_834Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pdbe-molstar@0.1.0 build: `npm run build-tsc && npm run build-extra && npm run build-webpack && npm run bundle-webcomponent`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pdbe-molstar@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

any idea what to do ?

**Comment by mandarsd** [comment]
@LivC182 If you check `package.json` you'll notice that Mol* dependency is imported as a github tar.gzip and not as a npm module. This was implemented to be able to utilise pre-built typescript modules of Mol*.
To build pdbe-molstar locally you'll have to manually build the Mol* package as well.
So After `npm install`, 
go to node_modules/molstar and do `npm run build` (you'll have to do this only once)
Finally run `npm run build` at the root and the implementation should compile without any issue.

**Comment by mandarsd** [comment]
NPM package updated with build/ 
Please use v0.1.1 for v0.x
