### ISSUE TITLE
Internal Server Error on structure retrieval

### ISSUE THREAD

**Issue by marnec** [PDBeurope/pdbe-molstar#10]
The endpoint used by PDBE-molstar is currently down and the plugin returns error:

```
Access to XMLHttpRequest at 'https://www.ebi.ac.uk/pdbe/model-server/v1/2nnu/full?encoding=bcif' from origin 'https://run.plnkr.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

tested on the examples found at [https://github.com/PDBeurope/pdbe-molstar/wiki]()

**Comment by mandarsd** [comment]
We experienced a technical issue yesterday due to a power blip. This has now been resolved and model-server and other service api endpoints are restored.
