### ISSUE TITLE
Adding several noncontinguos residues to visual.select

### ISSUE THREAD

**Issue by noeliaferruz** [PDBeurope/pdbe-molstar#12]
I'd like to add several residues at a time in a representation in visual.select().

According to the documentation can add a single residue, or add a set of contiguous residues that go from `start_residue_number` to `end_residue_number`. But I'd like to apply the representation to several noncontiguous residues, like residue 130, 120, and 150. Lists are not accepted.
This is the code:

```
var selectSections = [
            {
              struct_asym_id: 'A',
              residue_number: 130,
              color:{r:255,g:0,b:255},
              representation: 'spacefill'
            }
          ]

      viewerInstance.render(viewerContainer, options);
      viewerInstance.events.loadComplete.subscribe(() => {
                 viewerInstance.visual.select({ data: selectSections, nonSelectedColor: {r:255,g:255,b:255}});
});
```

Any ideas?

Thanks for the great work.

**Comment by noeliaferruz** [comment]
I downloaded and changed the code to allow arrays in residue_number.

**Comment by noeliaferruz** [comment]
How can I add a color pragmatically to the selection above? Colors get only added when no `sidechain` or `representation` are defined (so overpaiting cartoon)

**Comment by mandarsd** [comment]
You can use the existing functionality to add non-continues residues as well and for single residue you just have to mention the same for both start and end
Example -
`var selectSections = [
            {
              struct_asym_id: 'A',
              start_residue_number: 120,
              end_residue_number: 120,
              color:{r:255,g:0,b:255},
              representation: 'spacefill'
            },
            {
              struct_asym_id: 'A',
              start_residue_number: 150,
              end_residue_number: 150,
              color:{r:255,g:0,b:255},
              representation: 'spacefill'
            }
          ]

      viewerInstance.render(viewerContainer, options);
      viewerInstance.events.loadComplete.subscribe(() => {
                 viewerInstance.visual.select({ data: selectSections, nonSelectedColor: {r:255,g:255,b:255}});
});`

You'll have to extend the code a bit to apply color for different representations. For that you'll have to update the color value somewhere here https://github.com/PDBeurope/pdbe-molstar/blob/master/src/app/index.ts#L470 in your code

Hope this helps!

**Comment by noeliaferruz** [comment]
Thank you, very useful!

I might not be understanding how the representations add colors though. 
If I add a color to a cartoon representation, then it gets added with the `applyTheme` function here  https://github.com/PDBeurope/pdbe-molstar/blob/master/src/app/index.ts#L460  
The object `colorValue` looks like this:
`Object { selection: {…}, action: {…}, representations: [] }`, where actions contains `{name: "color" params: {…}}`

In  https://github.com/PDBeurope/pdbe-molstar/blob/master/src/app/index.ts#L470 the `add` function is used, and `values` doesn't contain `actions.params` object. If I include an `actions.param` object to be passed, no effect is produced. 

I tried to modify line 470 to use `applyTheme`, but then also no effect. I also tried to first `applyTheme` and then `add`, but then the spacefill representation was lost. So I am not sure how to proceed.

thanks a lot for your time.

**Comment by noeliaferruz** [comment]
ok, I just got it. I have to return first add the spacefill representation to structures fulfilling getStructuresWithSelection() and applyTheme (with color value) to those structures.

The problem is that this only works once. If I add a second set I get the error pivot.cell is undefined.
Here is the code:
```
if (param.representation)
  repr = param.representation;
defaultParams = component_1.StructureComponentManager.getAddParams(this.plugin, { allowNone: false, hideSelection: true, checkExisting: true });
defaultValues = param_definition_1.ParamDefinition.getDefaultValues(defaultParams);
defaultValues.options = { label: 'selection-by-script', checkExisting: true }; // change label later
values = tslib_1.__assign(tslib_1.__assign({}, defaultValues), {representation: repr});
structures = this.plugin.managers.structure.hierarchy.getStructuresWithSelection();
this.plugin.managers.structure.component.add(values, structures)
themeParams = component_1.StructureComponentManager.getThemeParams(this.plugin, structures);
colorValue = param_definition_1.ParamDefinition.getDefaultValues(themeParams);
colorValue.action.params = { color: param.color ? this.normalizeColor(param.color) : color_1.Color.fromRgb(255, 112, 3), opacity: 1 };

return [4 /*yield*/, this.plugin.managers.structure.component.applyTheme(colorValue, structures)];
```

And the error:
Uncaught (in promise) TypeError: pivot.cell is undefined

By the way, the rendering is great and fast !!:
![1CBS](https://user-images.githubusercontent.com/12035024/100675288-f7ae2d00-3366-11eb-8f78-9a52d68c1009.png)

**Comment by mandarsd** [comment]
Representations are added as independent component so the structure selection is not working. To accomplish this the individual representation theme should be set to uniform color.
I've added the functionality in the PDBe implementation itself -
https://github.com/PDBeurope/pdbe-molstar/commit/93e56ec31dd13807002837da202f5a2fbfa8c90f

Now you should be able to create the 3D view as shown in your image using the selection method. The only addition is that the representation color value should to be provide in 'representationColor' property separately. This is done to avoid breaking of any previous implementation.

**Comment by noeliaferruz** [comment]
This worked like a charm!
Thank you so much!

How would you like to be cited in publications and web resources?

**Comment by mandarsd** [comment]
You could cite these publications - 10.2312/molva.20181103 and http://dx.doi.org/10.1093/nar/gkx1070
For web-resources you could give credit using GitHub Star if you find the project useful :)  and I guess you would have already forked/ added the project in your package.json
