### ISSUE TITLE
Support loading Molstar States?

### ISSUE THREAD

**Issue by caseysteffen** [PDBeurope/pdbe-molstar#14]
Hi, is there a way to specify a saved Molstar Viewer state? maybe through loading a saved .molx file? 

thanks

**Comment by mandarsd** [comment]
Hi, Molstar viewer state download is an experimental feature in this plugin.
Please post your question in the core Molstar repository here - https://github.com/molstar/molstar/issues
I'm sure they will be able to help you with this functionality.
