### ISSUE TITLE
Show interactions between custom atoms

### ISSUE THREAD

**Issue by noeliaferruz** [PDBeurope/pdbe-molstar#15]
I am showing interactions as dashed lines in my application:

```
  auth_asym_id: bond.chain[0],
  auth_residue_number: bond.residues,
  representation: 'interactions',
  label: "Hydrogen bond network " + i,
  representationColor: color_palette[i]
```
This code will find interactions between the residues in bond.residues and add dashed lines when molstar thinks there is an interaction applicable. But how can I show an interaction between atom A and B, regardless of whether molstar think there is an interaction or not?

Otherwise, it would be enough to know what cutoffs is molstar using to plot hydrogen bonds so that I can perhaps start using the same cutoffs in my method. I am finding discrepancies between what I define as a hydrogen bond and what molstar shows.

Any ideas?

**Comment by mandarsd** [comment]
Please post this question in the core Molstar project repository here - https://github.com/molstar/molstar/issues
The interactions module developer should be able to answer your query.
