### ISSUE TITLE
Custom URL for loading density/maps/ccp4 files

### ISSUE THREAD

**Issue by jpattle** [PDBeurope/pdbe-molstar#24]
I was wondering whether it is possible to load custom ccp4 files into the pdbe molstar web component.

So far we have set up the pdbe molstar web component to load custom pdb files using the `custom-data-url` and `custom-data-format` attributes. Given that these custom files do not have associated maps in the www.ebi.ac.uk repository, using the `show-maps` attribute does not help. We have our own `.ccp4` format files that we would like to load into the component in the same way we have loaded the pdb files.

We have also tried to load these files by specifying `custom-data-format='ccp4'` but unfortunately it seems that is not the correct way to do it either as I get the error; `Error: ccp4 not supported.`.

Looking at the Molstar Viewer (https://molstar.org/viewer/) there are options to load densities into the viewer from a custom url. Is it possible to use these features in the pdbe molstar web component?

![image](https://user-images.githubusercontent.com/84507154/118977163-c6093c80-b96d-11eb-9c10-99fdc651b0d1.png)

Thanks in advance for your help!

**Comment by mandarsd** [comment]
Sorry, we do not support custom map data loading as we use 'Density server' (https://www.ebi.ac.uk/pdbe/densities/) in the PDBe implementation. You could fork this project and add the required functionality from the Molstar project (https://github.com/molstar/molstar/) for your use case.
