### ISSUE TITLE
Local PBD file not working

### ISSUE THREAD

**Issue by kennethliu64** [PDBeurope/pdbe-molstar#29]
I'm hosting a local version of a PDB file with changed residue numbers and only certain ligands. The file seems to open up fine on PyMol.

`customData:{ url:'CleanPdb.pdb', format: 'pdb', binary:true}`

I'm pathing to the correct file in the same directory, and it shows a blank viewer. I tried pathing to it through a web server and I'm having the same issue. Here's what it looks like:
<img width="391" alt="Screen Shot 2021-06-20 at 11 58 25 PM" src="https://user-images.githubusercontent.com/84150812/122705441-be1a1200-d223-11eb-837b-beb6eb6205aa.png">

**Comment by mandarsd** [comment]
The binary property should be set to false -
`customData:{ url:'CleanPdb.pdb', format: 'pdb', binary:false}`
