### ISSUE TITLE
what is the difference between pdbe-molstar and litemol?

### ISSUE THREAD

**Issue by wk989898** [PDBeurope/pdbe-molstar#31]

**Comment by mandarsd** [comment]
Molstar is a web-based open-source toolkit for the visualization and analysis of large-scale molecular data.
PDBe-molstar is an implementation of Molstar to cater 3D visualization across different PDBe services.

LiteMol was replaced by Molstar implementation last year. To know more about the Molstar project, please refer - https://github.com/molstar/molstar
