### ISSUE TITLE
Colouring (e.g. via select) atoms

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [PDBeurope/pdbe-molstar#32]
Hello,
Thank you for developing this nice tool!
I would like to ask if it is possible to colour certain atoms?

E.g., "select" function described here: https://github.com/PDBeurope/pdbe-molstar/wiki/3.-Helper-Methods#wiki-pages-box
had param called "atoms". Is it the way to colour atoms?

I attempted to colour atoms using this function and providing an array with atom IDs (e.g. ["1", "2", "3"]). But it does not seem to work. Could you tell me please what I am missing? Or there is another way of colouring atoms?

Thanks again,
Aliaksei

**Comment by mandarsd** [comment]
Hi,
atom_id parameter is now available with v1.2.0
