### ISSUE TITLE
Individually coloring residues with visual.select()

### ISSUE THREAD

**Issue by Fancien** [PDBeurope/pdbe-molstar#33]
Hi ! 

I'm currently integrating Mol* in a web project in which I would like to individually color the residues in protein structure based on a score associated with each residue.

As I understand the demo on helper functions, I have to create an array of selections in the following format:
{
  residue_number: i,
  color: score2RGB(score)
}
then give the whole list to viewerInstance.visual.select().

My issue is that if any selection in the array returns no residue, the whole select() function fails.

A specific example is PDB 5i81. If the array contains any residue with a residue number lower than 38, no coloring is done because the visual only contains residues 38 to 565.

Can I have any tip on how to circuvent this issue ? Or is there any other method to individually color residues in the protein structure ?

Best regards,
François Ancien

**Comment by mandarsd** [comment]
Hi,
The visual.select() api creates a single composite query from the list of data provided. As you have noticed, any invalid selection data results in cancelling the selection operation.

One way to make sure if the individual params in the list are valid is by using the viewerInstance.getLociForParams() api 
https://github.com/PDBeurope/pdbe-molstar/blob/master/src/app/index.ts#L394
If getLociForParams() returns an empty element list/ array then your param is invalid or have no match.

This solution is only visible if you have a small selection param list. If you are recolouring all/ huge list of residues then my suggestion would be to create and apply your own custom theme. You could refer to the 'Proteopedia-wrapper' example in Molstar GitHub and create your own implementation.
https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/
https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/coloring.ts
https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/index.html#L123
