### ISSUE TITLE
Loading custom data (e.g. local .pdb file)

### ISSUE THREAD

**Issue by benbutt** [PDBeurope/pdbe-molstar#36]
Hi,
I am trying to embed PDBe Molstar as a web component into HTML, as described in: https://github.com/PDBeurope/pdbe-molstar/wiki/2.-PDBe-Molstar-as-Web-component#steps-to-include-pdbe-molstar-as-a-web-component-in-a-web-application

I would like to load a local .pdb file using the `custom-data-url` attribute. 

1. I am unable to load a local .pdb or .cif  from an absolute or relative filepath using any of the provided code examples.
2. The example provided in the documentation is not currently working as the URL provided (https://www.ebi.ac.uk/pdbe/coordinates/1cbs/cartoon) points at an mmcif, although `custom-data-format="pdb"` is specified.

**Comment by mandarsd** [comment]
Hi
https://www.ebi.ac.uk/pdbe/coordinates/1cbs/cartoon points to a cif file. Setting `custom-data-format="cif"` works fine in the example. I have corrected the wiki documentation.
You'll have to make sure that your files are served via a server (localhost in case of local files) with the appropriate header and CORS settings.
