### ISSUE TITLE
Adding sidechain to region changes underlying colors

### ISSUE THREAD

**Issue by cbalbin-FIU** [PDBeurope/pdbe-molstar#37]
Hey,
First off, thanks for your great work on making molstar easier to integrate.

I am using pdbe-molstar to visualize the side-chains at some regions in AlphaFold predictions. The problem I am facing is that the spectrum colorings of the AlphaFold confidence disappears in regions where the side-chains are displayed.

For example (before showing side chains for region)
```javascript
var viewerInstance = new PDBeMolstarPlugin();

var options = {
    customData: { url: 'https://alphafold.ebi.ac.uk/files/AF-Q76EI6-F1-model_v1.cif', format: 'cif' },
    alphafoldView: true,
}

var viewerContainer = document.getElementById('myViewer');
viewerInstance.render(viewerContainer, options);
```

![AF-Q76EI6-F1](https://user-images.githubusercontent.com/76659347/135538761-471add3d-4e01-4257-b634-f3747701dc1b.png)

Now when I display side-chains for a small region, that region loses the AlphaFold confidence coloring
```javascript
var viewerInstance = new PDBeMolstarPlugin();

var options = {
    customData: { url: 'https://alphafold.ebi.ac.uk/files/AF-Q76EI6-F1-model_v1.cif', format: 'cif' },
    alphafoldView: true,
}

var viewerContainer = document.getElementById('myViewer');
viewerInstance.render(viewerContainer, options);



viewerInstance.events.loadComplete.subscribe(() => {
    viewerInstance.visual.select({ data: [{ struct_asym_id: 'A', start_residue_number: 10, end_residue_number: 15, sideChain: true }] })
    // or
    // viewerInstance.visual.select({ data: [{ struct_asym_id: 'A', start_residue_number: 10, end_residue_number: 15, representation: 'ball-and-stick' }] })

})

```

![AF-Q76EI6-F1 (1)](https://user-images.githubusercontent.com/76659347/135538992-b7d947f8-5298-45d2-ac54-b07be0708c8f.png)

The region where the side-chains are being displayed are now orange.
Is there a way to maintain the AF confidence coloring for the region in which side-chains are enable? 

Or even better, can I color everything, including the side chains by AF confidence?

Thanks for your time!

**Comment by mandarsd** [comment]
Hi,
The select method just supports uniform coloring. To accomplish the functionality you need, you could write your own method to just add side-chains. For that, you could refer - [https://github.com/PDBeurope/pdbe-molstar/blob/master/src/app/index.ts#L509](https://github.com/PDBeurope/pdbe-molstar/blob/master/src/app/index.ts#L509)
And after the addition of the side-chain, you will have to set its theme to `af-confidence`. For that, you'll have to use the `updateRepresentationTheme` method like here - [https://github.com/PDBeurope/pdbe-molstar/blob/master/src/app/index.ts#L525](https://github.com/PDBeurope/pdbe-molstar/blob/master/src/app/index.ts#L525)
