### ISSUE TITLE
Hiding a part of molecule

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [PDBeurope/pdbe-molstar#38]
Dear all,

Firstly, thanks again for the nice work! I am also really grateful for support and implementing features based on requests from people!

Is it possible to programmatically hide a part of a molecule (if I know which residues should be displayed, and the rest should not)?

Best regards,
Aliaksei

**Comment by mandarsd** [comment]
Hi Aliaksei,
It is definitely possible to implement the functionality you are looking for. We don't have any ready-to-use method in the PDBe implementation so you'll have to write some code for this. You could ask for some pointer in the Mol* repo here - [https://github.com/molstar/molstar/issues](https://github.com/molstar/molstar/issues)
