### ISSUE TITLE
Hide non-covalent interactions

### ISSUE THREAD

**Issue by JinyuanSun** [PDBeurope/pdbe-molstar#39]
Is that possible to disable all non-covalent interactions when click a residue?

**Comment by mandarsd** [comment]
You could switch off the click interactions behaviour by settings `selectInteractions` to false

It is the 20th option mentioned in the plugin params here - [https://github.com/PDBeurope/pdbe-molstar/wiki/1.-PDBe-Molstar-as-JS-plugin#plugin-parameters-options](https://github.com/PDBeurope/pdbe-molstar/wiki/1.-PDBe-Molstar-as-JS-plugin#plugin-parameters-options)
