### ISSUE TITLE
Displays a subset of protein molecules

### ISSUE THREAD

**Issue by Fanyini** [PDBeurope/pdbe-molstar#40]
Dear all,
Firstly, thanks again for the nice work! I am also really grateful for support and implementing features based on requests from people!
![1635490205(1)](https://user-images.githubusercontent.com/23491848/139389162-6f555a29-3d9d-4d0a-926f-f77235cf070f.jpg)
The figure above shows a molecular structure, which is composed of a complete molecular data (ribbon) and cavity data (sphere).
Now, I want to use pdbe to realize it. What should I do? As shown below, they are displayed in one page.
![1635490228(1)](https://user-images.githubusercontent.com/23491848/139390594-5b4caf40-a758-4235-b8b2-7b9175a9bd80.jpg)
Best regards,
Fanyin.

**Comment by mandarsd** [comment]
Hi, Please refer to the Mol* viewer documentation here - [https://molstar.org/viewer-docs/](https://molstar.org/viewer-docs/)
