### ISSUE TITLE
Option 'alphafoldview' is not working with PDB format

### ISSUE THREAD

**Issue by ebettler** [PDBeurope/pdbe-molstar#42]
With PDBe Molstar as JS plugin, AlphaFold confidence score colouring theme for AlphaFold model (option alphafoldview) is not working if the file loaded is in PDB format. It is working with cif format.
To test: 
go to url: https://embed.plnkr.co/plunk/WlRx73uuGA9EJbpn
In index.html windows:
change url with pdb extension (https://alphafold.ebi.ac.uk/files/AF-O15552-F1-model_v1.cif -> https://alphafold.ebi.ac.uk/files/AF-O15552-F1-model_v1.pdb)
change format: 'cif' -> format: 'pdb'
Protein change to gray !

**Comment by mandarsd** [comment]
The data required for colouring is only available in the cif file under the category '_ma_qa_metric_local'
that's why the colouring is limited to cif
