### ISSUE TITLE
`viewer.visual.<function>()` ignored immediately after `viewer.visual.update()`

### ISSUE THREAD

**Issue by marnec** [PDBeurope/pdbe-molstar#5]
I have a page whit an embedded viewerInstance. The page gives the user the possibility to chose the pdb structure to visualize in the viewerInstance. To show a new PDB I use the viewer.update() function which correctly fetches and visualizes a new PDB. However I also want to visualize specific chains so I would like to do `viewer.visual.select()` just after the new pdb has loaded: However this doesn't work:

```
viewerInstance.visual.update({moleculeId: pdb.id})
viewerInstance.visual.focus(...);
```

I noticed that the viewerInstance returns a Promise so I tried this but this also doesn't work:

```
viewerInstance.visual.update({moleculeId: pdb.id}).then( (d) => {
            this.viewerInstance.visual.focus(...);
          }
        );
```

I think I may be missing something. How am I supposed to `update()` to a new molecule and immediately show a specific chain or focus on a specific region?

**Comment by mandarsd** [comment]
There is a loadComplete event you can bind to -
`viewerInstance.visual.update({moleculeId: pdb.id});
viewerInstance.events.loadComplete.subscribe(() => {
	viewerInstance.visual.focus(...);
});`
This information is missing in the wiki, which I'll update now.

**Comment by mandarsd** [comment]
Updated the wiki with the available Custom events information - 
[Wiki Helper methods](https://github.com/PDBeurope/pdbe-molstar/wiki/3.-Helper-Methods)

**Comment by marnec** [comment]
Thank you. Last thing I noticed before leaving work today was that the viewer object had the `loadComplete` field and I was wondering if I could use it. Thanks I will check the new docs
