### ISSUE TITLE
programmatic access to mouse events

### ISSUE THREAD

**Issue by marnec** [PDBeurope/pdbe-molstar#8]
Hi, 
I searched in docs and examples but it seems that the API offers no way to access mouse events happening in the canvas.

I would like to prevent some default click behavior (e.g. focusing on right-clicked residues) and add some custom behaviors.

While I can catch clicks happening on the canvas it is very difficult (or impossible) to know where the click happened (residue or background) and to prevent default behavior.

Is this possible with the current API? Do you plan to add some or any of these functionalities? Alternatively, do you know of any workaround that could help me?

**Comment by mandarsd** [comment]
Hi,
Please refer to 'Custom Events' section [here ](https://github.com/PDBeurope/pdbe-molstar/wiki/3.-Helper-Methods) in the wiki docs. You can add listener for Click (Primary), Mouseover and Mouseout events.
Currently there is no provision to prevent / override default mouse event behaviour. I'll add this to our feature request list and check how we can provide this functionality generically using parameters.
As a workaround for now, you could fork the code and override the [defaults](https://github.com/molstar/molstar/blob/master/src/mol-plugin/behavior/dynamic/camera.ts#L19). Here is a [reference](https://github.com/PDBeurope/pdbe-molstar/blob/lig-env/src/app/index.ts#L71)

**Comment by mandarsd** [comment]
Hi,
The plugin v1.2.0 provides parameters to override mouse click behaviour. For details please refer `selectBindings ` and `focusBindings` parameters in the [plugin documentation](https://github.com/PDBeurope/pdbe-molstar/wiki/1.-PDBe-Molstar-as-JS-plugin)
